export const CATEGORIES = [
  'Teknoloji',
  'Beyaz Eşya',
  'Giyim & Moda',
  'Ayakkabı & Çanta',
  'Ev & Yaşam',
  'Mobilya & Dekorasyon',
  'Spor & Outdoor',
  'Kozmetik & Bakım',
  'Süpermarket',
  'Anne & Bebek',
  'Kitap & Kırtasiye',
  'Oyun & Oyuncak',
  'Seyahat',
  'Yemek & İçecek',
  'Sağlık',
  'Otomotiv',
  'Pet Shop',
  'Bahçe & Yapı',
];
